### ISSUE TITLE
How to get in touch with you?

### ISSUE THREAD

**Issue by kR105-zz** [ps4dev/libps4#4]
Do you have any email address where I can reach you? Or Twitter? Etc?

**Comment by psxdev** [comment]
I am back but i can't contact with Hitodama. I believe that libps4 is more developer/user friendly than PS4-SDK from Cturt. What do you think?

@hitodama  where are you?

**Comment by hitodama** [comment]
Hi guys :)

Sorry I left for a while for some personal stuff. I noticed you implemented the exploit. I did the same back in January, but seemingly nobody noticed (https://github.com/ps4dev/libps4-examples/tree/kexec-dev/kernel/kexec) - maybe because of the first comment of the unclean illogical kernel function or because it was on a branch? ;) Sadly I forgot to point you to it, probably because you seem more interested in the vita at that time.

I am not sure how much time I can currently invest into the project(s) but please leave me any requests or comments. If you got some neat ideas, please get to me ^^. I will make a twitter account (**hitochibito**), since I don't want to publish a mail publicly (I can give it to you there).

Back in January I dumped the kernel (https://gist.github.com/hitodama/fd612a6ebe925e75f0a6) and FS (https://gist.github.com/hitodama/1772e1a91168fc21b796) and started to implement a "run in kernel" function in the SDK (never finished it though) as well as a kernel SDK (never finished either). 

I'll upload my latest code tomorrow. It contains privilege escalation etc. - and I will also look what you and others have published and incorporate it. I like the dynamic symbol lookup fail0verflow implemented. Mine did not get that far :) I also had some problems with locks, but I used READ to trigger the exploit, from what I can see, you have the same kernel lock issues on shutdown and socket close(?). Will be fun to look into these things. Expect some pushes ;)

Sorry again, talk to you soon and gonna get the project up to date :)

PS: Oh, I also looked into your fork Antonio. I would like to integrate your changes as much as possible (for your convenience) but why are you changing the addresses Oo? If you change them the elf will not run on both environments ... I would prefer if we can stick to one, permanently.

**Comment by psxdev** [comment]
Glad to see that you come back to work.

I don't know what is the problem in my environment, (i have always ps4 camera attached to the system) with default addresses i got memory access problem loading my stuff so i use that values for personal use since september , i have not investigated where is the problem  but i had the same issue with CTurt code. 

I sent you my personal email on private we need to talk.

**Comment by hitodama** [comment]
I will look into the camera. It could be that it doesn't work because of a prior allocation. I talked to CTurt back then about that too. The address is chosen somewhat bad, because that's where the jit allocates from, and it seemingly has some internal tracking of where to allocate next. So if the camera forces some form of jit alloc, and I remember all these things correctly, I guess it could make the allocation fail. In that case I will probably adapt your addresses, or we define completely new ones, far away from the jit alloc.

**Comment by hitodama** [comment]
Hey guys, sorry for the delay. I did not find the time until now :( However I added some cool features that let you re-enter the kernel repeatedly (and also leave the process).

Regarding the cleanup of the exploit. In my view it is rather difficult. I am not sure why people add threads around the exploit because it's not the thread that is corrupted. It's the process ... (specifically the mutex of the knote associated with file descriptor, which is overritten, but still blocks the socket on cleanup). The only way to clean this I have found so far is to crash the process or close it. I was not able to recover or patch out the mutex. You can experience these issues when playing with the raised fd (try double close try reopen), you will find issues that lock the kernel.
The SDK now offers a "ps4KernelRun" which works around the issue, that we can not repeatedly enter the kernel via the exploit (because of the above). So, instead I patch syscall 172 to be a "callback" that runs user-land code. See `libps4-examples/kernel/kernel-run` for these features :)

**Comment by hitodama** [comment]
I will now look into your address issue Antonio and get back to you via mail.

**Comment by psxdev** [comment]
loading kernel-run.elf from ps4sh with ps4link is fine with changes needed in my environment
./ps4sh
ps4sh version 1.0
/Users/bigboss/.ps4shrc: No such file or directory
Connecting to fio ps4link ip 192.168.1.17
log: [HOST][INFO]: [PS4SH] Ready
log: [PS4][DEBUG]: [PS4LINK] Initialized and connected from pc/mac ready to receive commands
log: [PS4][DEBUG]: [PS4LINK] sock ps4link_fileio set 87 connected 1
log: [PS4][DEBUG]: [PS4LINK] Waiting for connection
ps4sh> ls
total 478
-rwxr-xr-x  1 bigboss  staff  38057 11 abr 00:35 kernel-run.elf
-rwxr-xr-x  1 bigboss  staff  19586 10 abr 18:46 pad.elf
-rwxr-xr-x  1 bigboss  staff  46178 10 abr 23:48 payload.elf
-rwxr-xr-x  1 bigboss  staff  69620 10 abr 23:49 ps4ftp.elf
-rwxr-xr-x  1 bigboss  staff  53252  3 abr 21:00 ps4sh
ps4sh> execelf kernel-run.elf
log: [HOST][DEBUG]: [PS4SH] argc=1 argv=host0:kernel-run.elf
log: [PS4][DEBUG]: [PS4LINK] commands listener received packet size (266)
log: [PS4][DEBUG]: [PS4LINK] Received command execelf argc=1 argv=host0:kernel-run.elf
log: [PS4][DEBUG]: [PS4LINK] file open req (host0:kernel-run.elf, 0 0)
log: [HOST][DEBUG]: [PS4SH] Opening kernel-run.elf flags 0
log: [HOST][DEBUG]: [PS4SH] Open return 7
log: [PS4][DEBUG]: [PS4LINK] file open reply received (ret 7)
log: [PS4][DEBUG]: [PS4LINK] file lseek req (fd: 7)
log: [HOST][DEBUG]: [PS4SH] 38057 result of lseek 0 offset 2 whence
log: [PS4][DEBUG]: [PS4LINK] ps4link_lseek_file: lseek reply received (ret 38057)
log: [PS4][DEBUG]: [PS4LINK] file lseek req (fd: 7)
log: [HOST][DEBUG]: [PS4SH] 0 result of lseek 0 offset 0 whence
log: [PS4][DEBUG]: [PS4LINK] ps4link_lseek_file: lseek reply received (ret 0)
log: [HOST][DEBUG]: [PS4SH] read 38057 bytes of file descritor 7
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: Reply said there's 38057 bytes to read (wanted 38057)
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 0  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 1  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 2  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 3  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 4  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 5  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 6  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 7  readed 4096
log: [PS4][DEBUG]: [PS4LINK] ps4link_read_file: chunk 8  readed 5289
log: [PS4][DEBUG]: [PS4LINK] ps4link_file: file close req (fd: 7)
log: [PS4][DEBUG]: [PS4LINK] ps4link_close_file: close reply received (ret 0)
log: [PS4][DEBUG]: [PS4LINK] ready to run elf
log: [PS4][DEBUG]: ps4ProtectedMemoryCreate(2127288) ->
log: [PS4][DEBUG]: [PS4LINK] elfLoaderLoad(88074d580, 200ed4000, 200ccc000) ->
log: [PS4][DEBUG]: [PS4LINK] elfLoaderLoad return 0
log: [PS4][DEBUG]: [PS4LINK] mm->main 200cce340
log: [PS4][DEBUG]: PS4LINK run [200ccc000 + elfEntry = 200cce340]
log: [PS4][DEBUG]: [PS4LINK] New elf thread UID: 0x8074C5A0
log: [PS4][DEBUG]: [PS4LINK] commands listener waiting for next command
log: [PS4][DEBUG]: [PS4LINK] Configuration pointer 880729d40, pointer_conf string 880729d40
log: [PS4][DEBUG]: [PS4LINK] ps4LinkRunElfMain
log: [PS4][INFO]: debugnet already initialized using configuration from ps4link
log: [PS4][INFO]: debugnet_initialized=1 SocketFD=84 logLevel=3
log: [PS4][INFO]: ready to have a lot of fun...
log: [PS4][DEBUG]: uid: 1
log: [PS4][DEBUG]: sys: -1
log: [PS4][DEBUG]: return: 42
log: [PS4][DEBUG]: moo: Cows go to kernel too ...
log: [PS4][DEBUG]: uid: 1
log: [PS4][DEBUG]: sys: 0
log: [PS4][DEBUG]: ps4KernelIsInKernel(): 0
log: [PS4][DEBUG]: ps4KernelDlSym(kernel_map): ffffffff832f6d70
log: [PS4][DEBUG]: ps4KernelDlSym(copyin): ffffffff82613cc0
log: [PS4][DEBUG]: uid: 0
log: [PS4][DEBUG]: [PS4LINK] ps4LinkRunElfMain mm->main return 0
ps4sh> execwhoami
log: [HOST][DEBUG]: [PS4SH] [PS4SH] argc=0 argv=
log: [PS4][DEBUG]: [PS4LINK] commands listener received packet size (266)
log: [PS4][DEBUG]: [PS4LINK] Received command execwhoami
log: [PS4][DEBUG]: [PS4LINK] UID: 0, GID: 0
log: [PS4][DEBUG]: [PS4LINK] commands listener waiting for next command
